export enum RepositoriesTypes {
    SEARCH_REPOSITORIES_START = 'SEARCH_REPOSITORIES_START',
    SEARCH_REPOSITORIES_SUCCESS = 'SEARCH_REPOSITORIES_SUCCESS',
    SEARCH_REPOSITORIES_ERROR = 'SEARCH_REPOSITORIES_ERROR',
}